export const breakfasts = {
  ru: [
    "Бутерброд с крабом",
    "Горячий сэндвич/бутерброд",
    "Яйца в хлебе",
    "Омлет",
    "Яичница",
    "Творог с сметаной",
    "Вафли творожные/картофельные",
    "Блинчики (если сделаете)",
    "Вафли (творог + сыр)",
    "Бутерброд с паштетом + огурец",
    "Бутерброды с колбасой",
    "Гречневая каша с маслом и яйцом",
    "Ленивая овсянка с йогуртом, ягодами и медом",
    "Сырники (из творога) с вареньем или сгущенкой",
    "Банановый смузи с овсянкой",
    "Тосты с авокадо и яйцом пашот",
    "Запеченные хлебцы с творожным сыром и лососем",
    "Рисовая каша на молоке с корицей и яблоком",
    "Запеканка из творога",
    "Пшенная каша с тыквой",
    "Овощной салат с яйцом",
    "Салат из брокколи с орехами",
    "Йогурт с фруктами и мюсли",
    "Печеночные оладьи",
    "Зелёная гречка с авокадо",
    "Салат с креветками и рукколой",
    "Французский тост с кленовым сиропом",
    "Шоколадные оладьи",
    "Круассан с ветчиной",
    "Тыквенный крем с орехами",
    "Каша из киноа с бананом",
    "Буррито с яичницей",
    "Миска с гранолой и орехами",
    "Салат из свежих огурцов и помидоров",
    "Каша из полбы с ягодами",
    "Печеная груша с мёдом",
    "Смузи-айс с шпинатом",
    "Тост с лососем и яйцом",
    "Яичница с сосисками",
    "Салат из листьев шпината и пармезана",
    "Сырные шарики с зеленью",
    "Домашний хлеб с яйцом и авокадо",
    "Капустники с морковью",
    "Перловая каша с горохом",
    "Чечевичный суп-пюре на завтрак",
    "Сэндвич с сыром и маслинами",
    "Греческий йогурт с мёдом",
    "Блинчики с маком",
    "Сало с чёрным хлебом",
    "Суп из курицы на завтрак",
    "Печеные яблоки с корицей",
    "Фруктовая салатная миска",
    "Тости с арахисовым маслом",
    "Картофельные оладьи",
    "Пудинг из чиа с ягодами",
    "Яичница с томатами",
    "Мюсли со свежими ягодами",
    "Суп из тыквы",
    "Каша из овсянки грубого помола",
    "Салат из свежих листьев",
    "Глазунья с беконом",
    "Кукурузная каша",
    "Творог с мёдом",
    "Салат из моркови",
  ],
  en: [
    "Sandwich with crab",
    "Hot sandwich",
    "Eggs in bread",
    "Omelette",
    "Scrambled eggs",
    "Cottage cheese with sour cream",
    "Mashed potato waffles",
    "Pancakes (if you make them)",
    "Cottage cheese and cheese waffles",
    "Pate sandwich with cucumber",
    "Sausage sandwiches",
    "Buckwheat porridge with butter and egg",
    "Lazy oatmeal with yogurt and honey",
    "Cheesecakes with jam",
    "Banana smoothie with oatmeal",
    "Avocado toast with poached egg",
    "Baked crispbreads with salmon",
    "Rice porridge with cinnamon and apple",
    "Cottage cheese casserole",
    "Millet porridge with pumpkin",
    "Vegetable salad with egg",
    "Broccoli salad with nuts",
    "Yogurt with fruits and granola",
    "Liver pancakes",
    "Green buckwheat with avocado",
    "Shrimp salad with arugula",
    "French toast with maple syrup",
    "Chocolate pancakes",
    "Ham and cheese croissant",
    "Pumpkin cream with nut topping",
    "Quinoa porridge with banana",
    "Breakfast burrito",
    "Granola bowl with nuts",
    "Fresh cucumber and tomato salad",
    "Spelt porridge with berries",
    "Baked pear with honey",
    "Spinach smoothie",
    "Salmon and egg toast",
    "Egg scramble with sausages",
    "Spinach and parmesan salad",
    "Cheese balls with greens",
    "Homemade bread with egg and avocado",
    "Cabbage fritters",
    "Lentil soup-puree",
    "Sandwich with olives and cheese",
    "Greek yogurt with honey",
    "Pancakes with poppy seeds",
    "Baked apples with cinnamon",
    "Fresh fruit bowl",
    "Toast with peanut butter",
    "Potato pancakes",
    "Chia pudding with berries",
    "Egg scramble with tomatoes",
    "Muesli with fresh berries",
    "Pumpkin soup",
    "Savory oatmeal",
    "Fresh leaf salad",
    "Fried eggs with bacon",
    "Corn porridge",
    "Honey drizzled cottage cheese",
    "Carrot salad",
  ],
  uk: [
    "Бутерброд із крабом",
    "Гарячий сендвіч/бутерброд",
    "Яйця в хлібі",
    "Омлет",
    "Яєчня",
    "Творог зі сметаною",
    "Вафлі з сиру/картоплі",
    "Млинці (якщо зробите)",
    "Вафлі (сир + сир)",
    "Бутерброд із паштетом + огірок",
    "Бутерброди з ковбасою",
    "Гречана каша з маслом і яйцем",
    "Лінива вівсянка з йогуртом, ягодами і медом",
    "Сирники з варенням або згущеним молоком",
    "Банановий смузі з вівсянкою",
    "Тости з авокадо і яйцем пашот",
    "Запечені хлібці з сиром та лососем",
    "Рисова каша з молоком, корицею і яблуком",
    "Запіканка з сиру",
    "Пшоняна каша з гарбузом",
    "Овочевий салат з яйцем",
    "Салат з броколі з горіхами",
    "Йогурт з фруктами і мюслі",
    "Печінкові оладки",
    "Зелена гречка з авокадо",
    "Салат із креветками і руколою",
    "Французький тост з кленовим сиропом",
    "Шоколадні оладки",
    "Круасан із шинкою",
    "Гарбузовий крем із горіхами",
    "Каша з кіноа з бананом",
    "Буріто з яєчнею",
    "Миска з гранолою і горіхами",
    "Салат зі свіжих огірків і помідорів",
    "Каша з полби з ягодами",
    "Запечена груша з медом",
    "Смузі-айс зі шпинатом",
    "Тост із лососем і яйцем",
    "Яєчня з сосисками",
    "Салат із листя шпинату і пармезану",
    "Сирні кульки із зеленню",
    "Домашній хліб із яйцем і авокадо",
    "Оладки з капусти та моркви",
    "Перлова каша з горохом",
    "Чечевична суп-пюре на сніданок",
    "Сендвіч із сиром і оливками",
    "Грецький йогурт із медом",
    "Млинці з маком",
    "Сало з чорним хлібом",
    "Суп із курки на сніданок",
    "Запечені яблука з корицею",
    "Фруктова миска-салат",
    "Тости з арахісовим маслом",
    "Картопляні оладки",
    "Пудинг із чіа з ягодами",
    "Яєчня з томатами",
    "Мюслі зі свіжими ягодами",
    "Суп із гарбуза",
    "Каша з вівсянки грубого помелу",
    "Салат зі свіжого листя",
    "Глазунья з беконом",
    "Кукурудзяна каша",
    "Сир із медом",
    "Салат з моркви",
  ],
};

export const dinners = {
  ru: [
    "Рис и котлеты",
    "Плов",
    "Паста с шампиньонами и филе",
    "Гречка по-купечески с курицей",
    "Колбаски + пюре",
    "Гуляш и картошка",
    "Макароны с фаршем и томатной пастой",
    "Картошка вареная и скумбрия/сельдь",
    "Овощи и филе на гриле",
    "Холодник",
    "Суп с лисичками",
    "Жареная картошка",
    "Тушеная капуста с кусочками свинины",
    "Запеченные куриные бедра с картофелем и специями",
    "Пшенная каша с курицей и овощами",
    "Куриные наггетсы с овощным салатом",
    "Клетски (картофельные или творожные) с грибным соусом",
    "Рагу из овощей с мясом",
    "Рыба, запеченная в фольге с лимоном и зеленью",
    "Чечевичный суп-пюре с гренками",
    "Лазанья из лаваша с фаршем и сыром",
    "Кабачковые оладьи с чесночным соусом",
    "Куриные отбивные с рисом",
    "Каша из киноа с овощами",
    "Утка с яблоками в духовке",
    "Телятина в сливочном соусе с рисом",
    "Запеченный лосось с овощами",
    "Куриные крылышки в соусе BBQ",
    "Запеканка из макарон с сыром и ветчиной",
    "Мясные фрикадельки с овощами",
    "Ризотто с тыквой и грибами",
    "Соте из баклажанов с чесноком",
    "Курица в кисло-сладком соусе с ананасами",
    "Паста с песто и курицей",
    "Запеченные мидии в сырном соусе",
    "Салат Цезарь с курицей",
    "Пельмени в сливочном соусе с сыром",
    "Домашняя солянка с мясом",
    "Суп Том Ям с морепродуктами",
    "Тушеная индейка с овощами",
    "Шашлык из свинины с тонким лавашом",
    "Картофель по-деревенски с чесночным соусом",
    "Курица под соусом терияки с рисом",
    "Фаршированные перцы с овощами и фаршем",
    "Паста Болоньезе",
    "Запеченные кабачки с помидорами и сыром",
    "Тартар из говядины с зеленью",
    "Запеканка с картофелем, грибами и сыром",
    "Хачапури по-аджарски",
    "Мусака (греческая запеканка с мясом и баклажанами)",
    "Крабовые котлеты с цукини",
    "Грибной крем-суп",
    "Плов с курицей и сухофруктами",
    "Стейк из говядины на гриле",
    "Шурпа с бараниной",
    "Щи с говядиной и капустой",
    "Суп харчо",
    "Дорадо, запечённая с пряными травами",
    "Кус-кус с овощами и курицей",
    "Свинина в кисло-соевом соусе",
    "Рагу из картофеля и говядины с квашеной капустой",
    "Куриная грудка с сыром и брокколи в духовке",
    "Паста с грибами и трюфельным маслом",
    "Свиные ребрышки с медовым соусом",
    "Говяжье рагу с красным вином и овощами",
    "Пельмени домашние жареные",
    "Овощной карри с рисом",
    "Куриное филе на пару с овощами",
    "Рыбные котлеты с картофельным пюре",
    "Домашние беляши",
    "Овощные крокеты с морковью и брокколи",
    "Мясной рулет с грибами",
    "Салат с тунцом, яйцом и помидорами",
    "Пицца с креветками и сыром",
    "Фаршированные шампиньоны с беконом",
    "Паста Карбонара",
    "Телячьи колбаски на гриле с гарниром",
    "Тыквенный суп с семечками",
    "Рагу с фасолью и колбасками",
    "Куриные рулетики с ветчиной и сыром",
    "Фалафель с овощами и йогуртовым соусом",
    "Бифштекс с глазуньей",
    "Жареная семга с лимоном",
    "Салат с кальмарами и овощами",
    "Крем-суп из брокколи с гренками",
    "Голубцы с мясом и рисом",
    "Бигос по-польски",
    "Сливочная куриная лапша",
    "Итальянская фокачча с розмарином",
    "Салат с печенью и гранатом",
    "Овощная запеканка с тыквой и шпинатом",
    "Куриные отбивные под сыром",
    "Пирог с мясом и грибами",
    "Баранина с картофелем и розмарином",
    "Салат Табуле с булгуром и овощами",
  ],
  en: [
    "Rice and cutlets",
    "Pilaf",
    "Pasta with mushrooms and fillet",
    "Buckwheat with chicken (merchant's style)",
    "Sausages + mashed potatoes",
    "Goulash with potatoes",
    "Pasta with minced meat and tomato paste",
    "Boiled potatoes and mackerel/herring",
    "Vegetables and grilled fillet",
    "Cold soup",
    "Soup with chanterelles",
    "Fried potatoes",
    "Stewed cabbage with pork",
    "Baked chicken thighs with potatoes and spices",
    "Millet porridge with chicken and vegetables",
    "Chicken nuggets with vegetable salad",
    "Dumplings with potatoes or cottage cheese and mushroom sauce",
    "Vegetable stew with meat",
    "Fish baked in foil with lemon and greens",
    "Lentil cream soup with croutons",
    "Lavash lasagna with minced meat and cheese",
    "Zucchini pancakes with garlic sauce",
    "Chicken schnitzel with rice",
    "Quinoa porridge with vegetables",
    "Duck with apples in the oven",
    "Veal in cream sauce with rice",
    "Baked salmon with vegetables",
    "BBQ chicken wings",
    "Macaroni casserole with cheese and ham",
    "Meatballs with vegetables",
    "Risotto with pumpkin and mushrooms",
    "Eggplant saute with garlic",
    "Chicken in sweet and sour sauce with pineapple",
    "Pasta with pesto and chicken",
    "Baked mussels in cheese sauce",
    "Caesar salad with chicken",
    "Pelmeni in cream cheese sauce",
    "Homemade meat solyanka",
    "Tom Yum soup with seafood",
    "Stewed turkey with vegetables",
    "Pork skewers with thin lavash",
    "Village-style potatoes with garlic sauce",
    "Chicken in teriyaki sauce with rice",
    "Stuffed bell peppers with vegetables and meat",
    "Pasta Bolognese",
    "Baked zucchini with tomatoes and cheese",
    "Beef tartare with greens",
    "Casserole with potatoes, mushrooms, and cheese",
    "Adjarian khachapuri",
    "Greek-style moussaka (meat and eggplant casserole)",
    "Crab cutlets with zucchini",
    "Creamy mushroom soup",
    "Pilaf with chicken and dried fruits",
    "Grilled beef steak",
    "Shurpa with lamb",
    "Cabbage soup with beef",
    "Kharcho soup",
    "Baked dorado with herbs",
    "Couscous with vegetables and chicken",
    "Pork in sweet soy sauce",
    "Stew with potatoes, beef, and sauerkraut",
    "Chicken breast with broccoli and cheese in the oven",
    "Pasta with mushrooms and truffle oil",
    "Pork ribs with honey sauce",
    "Beef stew with red wine and vegetables",
    "Fried homemade dumplings",
    "Vegetable curry with rice",
    "Steamed chicken fillet with vegetables",
    "Fish cutlets with mashed potatoes",
    "Homemade belyash",
    "Vegetable croquettes with carrots and broccoli",
    "Meatloaf with mushrooms",
    "Tuna salad with egg and tomatoes",
    "Shrimp and cheese pizza",
    "Stuffed mushrooms with bacon",
    "Pasta Carbonara",
    "Veal sausages on the grill with side dish",
    "Pumpkin soup with seeds",
    "Stew with beans and sausages",
    "Chicken rolls with ham and cheese",
    "Falafel with vegetables and yogurt sauce",
    "Beefsteak with fried egg",
    "Fried salmon with lemon",
    "Squid salad with vegetables",
    "Creamy broccoli soup with croutons",
    "Cabbage rolls with meat and rice",
    "Polish bigos",
    "Creamy chicken noodle soup",
    "Italian focaccia with rosemary",
    "Liver salad with pomegranate",
    "Vegetable casserole with pumpkin and spinach",
    "Chicken schnitzel with cheese",
    "Pie with meat and mushrooms",
    "Lamb with potatoes and rosemary",
    "Tabbouleh salad with bulgur and vegetables",
  ],
  uk: [
    "Рис із котлетами",
    "Плов",
    "Паста з грибами та філе",
    "Гречка по-купецьки з куркою",
    "Ковбаски + картопляне пюре",
    "Гуляш з картоплею",
    "Макарони з фаршем і томатною пастою",
    "Варена картопля і скумбрія/оселедець",
    "Овочі та філе на грилі",
    "Холодник",
    "Суп з лисичками",
    "Смажена картопля",
    "Тушкована капуста з шматочками свинини",
    "Запечені курячі стегна з картоплею та спеціями",
    "Пшоняна каша з куркою та овочами",
    "Курячі нагетси з овочевим салатом",
    "Кльоцки (картопляні або сирні) з грибним соусом",
    "Рагу з овочів з м'ясом",
    "Риба, запечена у фользі з лимоном і зеленню",
    "Суп-пюре з сочевиці з грінками",
    "Лазанья з лаваша з фаршем та сиром",
    "Оладки з кабачків із часниковим соусом",
    "Курячі відбивні з рисом",
    "Каша із кіноа з овочами",
    "Качка з яблуками в духовці",
    "Телятина у вершковому соусі з рисом",
    "Запечений лосось з овочами",
    "Курячі крильця в соусі BBQ",
    "Запіканка з макаронів із сиром та шинкою",
    "Фрикадельки з овочами",
    "Різотто з гарбузом і грибами",
    "Соте з баклажанів із часником",
    "Курка в кисло-солодкому соусі з ананасом",
    "Паста з песто і куркою",
    "Запечені мідії в сирному соусі",
    "Салат Цезар з куркою",
    "Пельмені у вершковому соусі із сиром",
    "Домашня солянка з м'ясом",
    "Суп Том Ям із морепродуктами",
    "Тушкована індичка з овочами",
    "Шашлик зі свинини у тонкому лаваші",
    "Картопля по-селянськи з часниковим соусом",
    "Курка у соусі теріякі з рисом",
    "Фаршировані болгарські перці з овочами",
    "Паста Болоньєзе",
    "Запечені кабачки з помідорами та сиром",
    "Тартар із яловичини із зеленню",
    "Запіканка з картоплі, грибів і сиру",
    "Хачапурі по-аджарськи",
    "Мусака (грецька запіканка з баклажанами та м'ясом)",
    "Крапові котлети із цукіні",
    "Суп-крем із грибів",
    "Плов із куркою та сухофруктами",
    "Стейк зі смаженої яловичини",
    "Шурпа із баранини",
    "Щі з яловичиною та капустою",
    "Суп харчо",
    "Дорадо, запечена із пряними травами",
    "Кус-кус із овочами і куркою",
    "Свинина у кисло-соєвому соусі",
    "Рагу з картоплі, яловичини і квашеної капусти",
    "Куряча грудка із сиром та броколі у духовці",
    "Паста з грибами та трюфельним маслом",
    "Свинячі реберця в медовому соусі",
    "Тушкована яловичина з червоним вином та овочами",
    "Смажені домашні пельмені",
    "Овочеве каррі із рисом",
    "Куряче філе на пару із овочами",
    "Рибні котлети із картопляним пюре",
    "Домашні біляші",
    "Овочеві крокети з морквою та броколі",
    "М'ясний рулет із грибами",
    "Салат із тунцем, яйцем і помідорами",
    "Піца з креветками та сиром",
    "Фаршировані шампіньйони з беконом",
    "Паста Карбонара",
    "Телячі ковбаски на грилі з гарніром",
    "Суп із гарбуза з насінням",
    "Рагу із квасолі й ковбасою",
    "Курячі рулети зі шинкою та сиром",
    "Фалафель із овочами та йогуртовим соусом",
    "Бефстроганов із яйцем",
    "Смажений лосось із лимоном",
    "Салат з кальмарами та овочами",
    "Крем-суп із броколі з грінками",
    "Голубці з м'ясом і рисом",
    "Польський бігос",
    "Кремова куряча локшина",
    "Італійська фокачча з розмарином",
    "Салат із печінкою та гранатом",
    "Овочева запіканка з гарбузом і шпинатом",
    "Курячі відбивні під сиром",
    "Пиріг із м'ясом та грибами",
    "Баранина з картоплею і розмарином",
    "Салат Табуле із булгуром та овочами",
  ],
};